version: '3'

services:
  db:
    image: mariadb
    environment:
      MYSQL_DATABASE: battlesnake
      MYSQL_USER: snake
      MYSQL_PASSWORD: battle
      MYSQL_ROOT_PASSWORD: groot
    volumes:
      - ./volumes/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306

  panel:
    image: phpmyadmin
    environment:
      PMA_USER: snake
      PMA_PASSWORD: battle
    ports:
      - 3064:80
